services:
  espn_historical:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.espn_historical
    container_name: espn_historical
    depends_on:
      postgres_db:
        condition: service_healthy
        restart: True
    env_file: .env.dev
    volumes:
      - .:/app
    command: python3.11 main.py  --scraper espn --mode  sync --timeframe historical
  
  espn_latest:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.espn_latest
    container_name: espn_latest
    depends_on:
      postgres_db:
        condition: service_healthy
        restart: True
    env_file: .env.dev
    volumes:
      - .:/app
  
  judges_async_historical:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.judges_async_historical
    container_name: judges_async_historical
    depends_on:
      postgres_db:
        condition: service_healthy
        restart: True
    env_file: .env.dev
    volumes:
      - .:/app
  
  judges_async_latest:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.judges_async_latest
    container_name: judges_async_latest
    env_file: .env.dev
    volumes:
      - .:/app
  
  judges_sync_historical:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.judges_sync_historical
    container_name: judges_sync_historical
    depends_on:
      postgres_db:
        condition: service_healthy
        restart: True
    env_file: .env.dev
    volumes:
      - .:/app  
  
  judges_sync_latest:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.judges_sync_latest
    container_name: judges_sync_latest
    depends_on:
      postgres_db:
        condition: service_healthy
        restart: True
    env_file: .env.dev
    volumes:
      - .:/app  
  
  odds_scraping:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.odds_scraping
    container_name: odds_scraping
    depends_on:
      postgres_db:
        condition: service_healthy
        restart: True
    env_file: .env.dev
    volumes:
      - .:/app
  
  ufc_upcoming:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.ufc_upcoming
    container_name: ufc_upcoming
    depends_on:
      postgres_db:
        condition: service_healthy
        restart: True
    env_file: .env.dev
    volumes:
      - .:/app
  
  ufc_latest:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.ufc_latest
    container_name: ufc_latest
    depends_on:
      postgres_db:
        condition: service_healthy
        restart: True
    env_file: .env.dev
    volumes:
      - .:/app
    
  postgres_db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    container_name: postgres_dbx
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file: .env.dev
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - postgres_network
  
networks:
  postgres_network:
    driver: bridge
