# Dockerfile.espn
FROM python:3.11

# 1. Set a working directory
WORKDIR /app

# 2. Copy requirements and install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN playwright install chromium
RUN playwright install-deps

# # 3. Copy the code
COPY src/scrapers ./scrapers
COPY src/main.py .
# COPY . .

# 4. Default command is ESPN historical, for example
CMD ["python3.11", "src/main.py", "--scraper", "espn", "--mode", "sync", "--timeframe", "historical"]
