##TODO: SCRIPT THAT WILL HELP US FEATURE ENGINEER THE PRECOMP DATA ITERATIVELY FROM WHERE OUR DATA ENDS (2022/10)
## ALL THE WAY UNTIL PRESENT DAY
## ALSO NEED THE SCRIPT TO CONTINOUSLY CALCULATE THIS FOR EVERY NEW FIGHT THAT HAPPENS FOR THE RESPECTIVE FIGHTERS

## BEST TO DO THIS ONCE WE PUSH TO POSTGRES, AS THIS ALLOWS FOR EASY ACCESSIBILITY DUE TO THE STRUCTURE OF THE DATA WE ARE HANDLING