## TODO: SCIPT HERE TO MATCH THE ODDS, JUDGING, AND UFCSTATS DATABASES BASED ON FUZZY MATCHING OF NAMES, DATES, AND LOCATIONS. 
## WE WILL USE THE UFCSTATS DATABASE AS THE BASE AND THEN MATCH THE OTHER TWO DATABASES TO IT. 
## ie. use the event and fight ids from the ufcstats database (this is the end part of the url)